.importzp zp_var
.importzp zp_world_addr
.importzp zp_buttons_1_curr_frame
.importzp zp_buttons_1_prev_frame
.importzp zp_buttons_1_pressed
.importzp zp_buttons_2_curr_frame
.importzp zp_buttons_2_prev_frame
.importzp zp_buttons_2_pressed
.importzp zp_nmi_retraces

.importzp zp_cursor_index_pos
.importzp zp_cursor_vertical_pos

.importzp zp_prng_seed
.importzp zp_dice_1
.importzp zp_dice_2
.importzp zp_dice_combined

.importzp zp0
.importzp zp1

.importzp Res
.importzp ResHi

.import vram_draw_buffer
.import vram_draw_buffer_size

.define CURSOR_X_ADDR $0201